name: ns_ideas
description: "projects app for youtube"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_database: ^10.2.0
  firebase_core: ^2.14.0
  cloud_firestore: ^4.7.0
  carousel_slider: ^4.2.1
  url_launcher: ^6.1.11
  youtube_player_flutter: ^8.1.2
  fluttertoast: ^8.2.1
  email_validator: ^2.1.17
  firebase_auth: ^4.6.0

  photo_view: ^0.14.0
  cached_network_image: ^3.2.3
  webview_flutter: ^4.2.0
  intl: ^0.18.1
  flutter_staggered_animations: ^1.1.1
  flutter_local_notifications: ^15.1.1
  firebase_messaging: ^14.6.1
  marquee: ^2.2.3
  visibility_detector: ^0.4.0+2
  mailer: ^6.0.1
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
#flutter_launcher_icons:
#  android: true
#  ios: true
#  image_path: "assets/logo.png"


  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
