// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYxgAkrusk6Ogu7QdL9w10gSw9iZAt0YM',
    appId: '1:512397462005:web:5e6b83b29c7f113baf78bc',
    messagingSenderId: '512397462005',
    projectId: 'prokoni',
    authDomain: 'prokoni.firebaseapp.com',
    storageBucket: 'prokoni.appspot.com',
    measurementId: 'G-EGKM49886V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVb-_KOjpg7bc9CTsizb9eSJgIUrG3imY',
    appId: '1:512397462005:android:cbf871945cce71ccaf78bc',
    messagingSenderId: '512397462005',
    projectId: 'prokoni',
    storageBucket: 'prokoni.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsTSsLsw2kxVdQrmpV08-uBN7btkCF_tg',
    appId: '1:512397462005:ios:14d879537cb33a0daf78bc',
    messagingSenderId: '512397462005',
    projectId: 'prokoni',
    storageBucket: 'prokoni.appspot.com',
    iosClientId: '512397462005-20r089tqeo6lvcg6n23ck3459imksh35.apps.googleusercontent.com',
    iosBundleId: 'com.nimmalasujith.nsIdeas',
  );
}
