// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYxgAkrusk6Ogu7QdL9w10gSw9iZAt0YM',
    appId: '1:512397462005:web:5e6b83b29c7f113baf78bc',
    messagingSenderId: '512397462005',
    projectId: 'prokoni',
    authDomain: 'prokoni.firebaseapp.com',
    storageBucket: 'prokoni.appspot.com',
    measurementId: 'G-EGKM49886V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVb-_KOjpg7bc9CTsizb9eSJgIUrG3imY',
    appId: '1:512397462005:android:54ebcd089ab07ceaaf78bc',
    messagingSenderId: '512397462005',
    projectId: 'prokoni',
    storageBucket: 'prokoni.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsTSsLsw2kxVdQrmpV08-uBN7btkCF_tg',
    appId: '1:512397462005:ios:5546854a07150889af78bc',
    messagingSenderId: '512397462005',
    projectId: 'prokoni',
    storageBucket: 'prokoni.appspot.com',
    iosClientId: '512397462005-tklrcadqpnkogde79hejmaknq9p3rt8l.apps.googleusercontent.com',
    iosBundleId: 'com.example.nsideas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsTSsLsw2kxVdQrmpV08-uBN7btkCF_tg',
    appId: '1:512397462005:ios:61224eed5d4e8deaaf78bc',
    messagingSenderId: '512397462005',
    projectId: 'prokoni',
    storageBucket: 'prokoni.appspot.com',
    iosClientId: '512397462005-rd4uomj2qkc5ufcup5alj9f9rpggr070.apps.googleusercontent.com',
    iosBundleId: 'com.example.nsideas.RunnerTests',
  );
}
